### ISSUE TITLE
uninitialized constant Passbook

### ISSUE THREAD

**Issue by zmitzie** [max-power/passbook#1]
I was going through your instructions to set it up, and I got an "uninitialized constant Passbook", on the first line " Passbook::Authority.new(File.read("/path/to/certificate.p12"), "secret-password") ". I generated my certificate and I verified the passTypeIdentifier (from the Developer Portal) and also that teamIdentified that are correct. I added the gem to the Gemfile pointing to the git repo. Am I missing something? @max-power 

Thanks in advance!

**Comment by max-power** [comment]
Did you require the gem?

**Comment by zmitzie** [comment]
You are right, I thought adding it in the Gemfile was enough. Works like a charm now :)
